// Theme definitions — each maps CSS variable names to canonical hex values.
// All colors are sourced from the official published palettes of each design system.
// The default theme (Catppuccin Mocha) uses the @theme block values and has no overrides.

export interface ThemeDefinition {
  readonly id: string;
  readonly name: string;
  readonly category: 'dark' | 'light';
  readonly colors: Readonly<Record<string, string>>;
}

const DEFAULT_THEME_ID = 'catppuccin-mocha';

// Radix Mauve — accessibility-engineered 12-step dark scale
const radixMauve: ThemeDefinition = {
  id: 'radix-mauve',
  name: 'Radix Mauve',
  category: 'dark',
  colors: {
    '--color-board-bg': '#121113',
    '--color-board-surface': '#1a191b',
    '--color-board-surface-hover': '#2b292d',
    '--color-board-surface-alt': '#121113',
    '--color-board-surface-elevated': '#323035',
    '--color-board-surface-overlay': '#3c393f',
    '--color-board-border': '#49474e',
    '--color-board-border-hover': '#625f69',
    '--color-board-text': '#eeeef0',
    '--color-board-text-muted': '#c8c6d0',
    '--color-board-text-faint': '#706d78',
    '--color-board-text-subtle': '#908d99',
    '--color-board-text-bright': '#ffffff',
    '--color-board-accent': '#70b8ff',
    '--color-board-red': '#ff9592',
    '--color-board-orange': '#ffa057',
    '--color-board-yellow': '#ffca16',
    '--color-board-green': '#3dd68c',
    '--color-board-purple': '#baa7ff',
    '--color-board-cyan': '#4ccce6',
    '--color-board-teal': '#0bd8b6',
    '--color-phase-specify': '#70b8ff',
    '--color-phase-plan': '#baa7ff',
    '--color-phase-tasks': '#ffa057',
    '--color-phase-implement': '#3dd68c',
    '--color-phase-summary': '#f65cb6',
    '--color-phase-review': '#0bd8b6',
    '--color-phase-unknown': '#6f6d78',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.6)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.5)',
  },
};

// Dracula — draculatheme.com
const dracula: ThemeDefinition = {
  id: 'dracula',
  name: 'Dracula',
  category: 'dark',
  colors: {
    '--color-board-bg': '#282a36',
    '--color-board-surface': '#21222c',
    '--color-board-surface-hover': '#44475a',
    '--color-board-surface-alt': '#282a36',
    '--color-board-surface-elevated': '#44475a',
    '--color-board-surface-overlay': '#4d4f5e',
    '--color-board-border': '#6272a4',
    '--color-board-border-hover': '#7284b8',
    '--color-board-text': '#f8f8f2',
    '--color-board-text-muted': '#6272a4',
    '--color-board-text-faint': '#545a78',
    '--color-board-text-subtle': '#6272a4',
    '--color-board-text-bright': '#ffffff',
    '--color-board-accent': '#8be9fd',
    '--color-board-red': '#ff5555',
    '--color-board-orange': '#ffb86c',
    '--color-board-yellow': '#f1fa8c',
    '--color-board-green': '#50fa7b',
    '--color-board-purple': '#bd93f9',
    '--color-board-cyan': '#8be9fd',
    '--color-board-teal': '#50fa7b',
    '--color-phase-specify': '#8be9fd',
    '--color-phase-plan': '#bd93f9',
    '--color-phase-tasks': '#ffb86c',
    '--color-phase-implement': '#50fa7b',
    '--color-phase-summary': '#ff79c6',
    '--color-phase-review': '#8be9fd',
    '--color-phase-unknown': '#6272a4',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.5)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.4)',
  },
};

// Tokyo Night — github.com/folke/tokyonight.nvim
const tokyoNight: ThemeDefinition = {
  id: 'tokyo-night',
  name: 'Tokyo Night',
  category: 'dark',
  colors: {
    '--color-board-bg': '#1a1b26',
    '--color-board-surface': '#1f2335',
    '--color-board-surface-hover': '#292e42',
    '--color-board-surface-alt': '#1a1b26',
    '--color-board-surface-elevated': '#33384e',
    '--color-board-surface-overlay': '#3b4261',
    '--color-board-border': '#3b4261',
    '--color-board-border-hover': '#565f89',
    '--color-board-text': '#c0caf5',
    '--color-board-text-muted': '#565f89',
    '--color-board-text-faint': '#444b6a',
    '--color-board-text-subtle': '#565f89',
    '--color-board-text-bright': '#ffffff',
    '--color-board-accent': '#7aa2f7',
    '--color-board-red': '#f7768e',
    '--color-board-orange': '#ff9e64',
    '--color-board-yellow': '#e0af68',
    '--color-board-green': '#9ece6a',
    '--color-board-purple': '#bb9af7',
    '--color-board-cyan': '#7dcfff',
    '--color-board-teal': '#73daca',
    '--color-phase-specify': '#7aa2f7',
    '--color-phase-plan': '#bb9af7',
    '--color-phase-tasks': '#ff9e64',
    '--color-phase-implement': '#9ece6a',
    '--color-phase-summary': '#ff007c',
    '--color-phase-review': '#73daca',
    '--color-phase-unknown': '#565f89',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.6)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.5)',
  },
};

// One Dark — github.com/atom/one-dark-syntax
const oneDark: ThemeDefinition = {
  id: 'one-dark',
  name: 'One Dark',
  category: 'dark',
  colors: {
    '--color-board-bg': '#282c34',
    '--color-board-surface': '#2c313c',
    '--color-board-surface-hover': '#3e4452',
    '--color-board-surface-alt': '#282c34',
    '--color-board-surface-elevated': '#3e4452',
    '--color-board-surface-overlay': '#4b5263',
    '--color-board-border': '#4b5263',
    '--color-board-border-hover': '#636d83',
    '--color-board-text': '#abb2bf',
    '--color-board-text-muted': '#5c6370',
    '--color-board-text-faint': '#4b5263',
    '--color-board-text-subtle': '#5c6370',
    '--color-board-text-bright': '#ffffff',
    '--color-board-accent': '#61afef',
    '--color-board-red': '#e06c75',
    '--color-board-orange': '#d19a66',
    '--color-board-yellow': '#e5c07b',
    '--color-board-green': '#98c379',
    '--color-board-purple': '#c678dd',
    '--color-board-cyan': '#56b6c2',
    '--color-board-teal': '#56b6c2',
    '--color-phase-specify': '#61afef',
    '--color-phase-plan': '#c678dd',
    '--color-phase-tasks': '#d19a66',
    '--color-phase-implement': '#98c379',
    '--color-phase-summary': '#e06c75',
    '--color-phase-review': '#56b6c2',
    '--color-phase-unknown': '#5c6370',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.5)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.4)',
  },
};

// Rosé Pine — rosepinetheme.com
const rosePine: ThemeDefinition = {
  id: 'rose-pine',
  name: 'Rosé Pine',
  category: 'dark',
  colors: {
    '--color-board-bg': '#191724',
    '--color-board-surface': '#1f1d2e',
    '--color-board-surface-hover': '#26233a',
    '--color-board-surface-alt': '#191724',
    '--color-board-surface-elevated': '#2a2837',
    '--color-board-surface-overlay': '#393552',
    '--color-board-border': '#524f67',
    '--color-board-border-hover': '#6e6a86',
    '--color-board-text': '#e0def4',
    '--color-board-text-muted': '#908caa',
    '--color-board-text-faint': '#6e6a86',
    '--color-board-text-subtle': '#817c9c',
    '--color-board-text-bright': '#ffffff',
    '--color-board-accent': '#c4a7e7',
    '--color-board-red': '#eb6f92',
    '--color-board-orange': '#ea9a97',
    '--color-board-yellow': '#f6c177',
    '--color-board-green': '#9ccfd8',
    '--color-board-purple': '#c4a7e7',
    '--color-board-cyan': '#9ccfd8',
    '--color-board-teal': '#3e8fb0',
    '--color-phase-specify': '#3e8fb0',
    '--color-phase-plan': '#c4a7e7',
    '--color-phase-tasks': '#f6c177',
    '--color-phase-implement': '#9ccfd8',
    '--color-phase-summary': '#eb6f92',
    '--color-phase-review': '#3e8fb0',
    '--color-phase-unknown': '#6e6a86',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.6)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.5)',
  },
};

// Catppuccin Mocha — default. No color overrides needed; uses @theme CSS values as-is.
const catppuccinMocha: ThemeDefinition = {
  id: DEFAULT_THEME_ID,
  name: 'Catppuccin Mocha',
  category: 'dark',
  colors: {},
};

// Gruvbox Dark — github.com/morhetz/gruvbox
const gruvboxDark: ThemeDefinition = {
  id: 'gruvbox-dark',
  name: 'Gruvbox Dark',
  category: 'dark',
  colors: {
    '--color-board-bg': '#282828',
    '--color-board-surface': '#3c3836',
    '--color-board-surface-hover': '#504945',
    '--color-board-surface-alt': '#282828',
    '--color-board-surface-elevated': '#504945',
    '--color-board-surface-overlay': '#665c54',
    '--color-board-border': '#665c54',
    '--color-board-border-hover': '#7c6f64',
    '--color-board-text': '#ebdbb2',
    '--color-board-text-muted': '#a89984',
    '--color-board-text-faint': '#7c6f64',
    '--color-board-text-subtle': '#928374',
    '--color-board-text-bright': '#fbf1c7',
    '--color-board-accent': '#83a598',
    '--color-board-red': '#fb4934',
    '--color-board-orange': '#fe8019',
    '--color-board-yellow': '#fabd2f',
    '--color-board-green': '#b8bb26',
    '--color-board-purple': '#d3869b',
    '--color-board-cyan': '#83a598',
    '--color-board-teal': '#8ec07c',
    '--color-phase-specify': '#83a598',
    '--color-phase-plan': '#d3869b',
    '--color-phase-tasks': '#fe8019',
    '--color-phase-implement': '#b8bb26',
    '--color-phase-summary': '#fb4934',
    '--color-phase-review': '#8ec07c',
    '--color-phase-unknown': '#928374',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.5)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.4)',
  },
};

// Solarized Dark — ethanschoonover.com/solarized
const solarizedDark: ThemeDefinition = {
  id: 'solarized-dark',
  name: 'Solarized Dark',
  category: 'dark',
  colors: {
    '--color-board-bg': '#002b36',
    '--color-board-surface': '#073642',
    '--color-board-surface-hover': '#0a4a5c',
    '--color-board-surface-alt': '#002b36',
    '--color-board-surface-elevated': '#0a4a5c',
    '--color-board-surface-overlay': '#155566',
    '--color-board-border': '#586e75',
    '--color-board-border-hover': '#657b83',
    '--color-board-text': '#93a1a1',
    '--color-board-text-muted': '#657b83',
    '--color-board-text-faint': '#506369',
    '--color-board-text-subtle': '#5b7279',
    '--color-board-text-bright': '#fdf6e3',
    '--color-board-accent': '#268bd2',
    '--color-board-red': '#dc322f',
    '--color-board-orange': '#cb4b16',
    '--color-board-yellow': '#b58900',
    '--color-board-green': '#859900',
    '--color-board-purple': '#6c71c4',
    '--color-board-cyan': '#2aa198',
    '--color-board-teal': '#2aa198',
    '--color-phase-specify': '#268bd2',
    '--color-phase-plan': '#6c71c4',
    '--color-phase-tasks': '#cb4b16',
    '--color-phase-implement': '#859900',
    '--color-phase-summary': '#d33682',
    '--color-phase-review': '#2aa198',
    '--color-phase-unknown': '#586e75',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.5)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.4)',
  },
};

// Solarized Light — ethanschoonover.com/solarized
const solarizedLight: ThemeDefinition = {
  id: 'solarized-light',
  name: 'Solarized Light',
  category: 'light',
  colors: {
    '--color-board-bg': '#fdf6e3',
    '--color-board-surface': '#eee8d5',
    '--color-board-surface-hover': '#e6dfcc',
    '--color-board-surface-alt': '#fdf6e3',
    '--color-board-surface-elevated': '#ddd6c1',
    '--color-board-surface-overlay': '#d3cbb7',
    '--color-board-border': '#93a1a1',
    '--color-board-border-hover': '#839496',
    '--color-board-text': '#002b36',
    '--color-board-text-muted': '#073642',
    '--color-board-text-faint': '#839496',
    '--color-board-text-subtle': '#657b83',
    '--color-board-text-bright': '#002b36',
    '--color-board-accent': '#268bd2',
    '--color-board-red': '#dc322f',
    '--color-board-orange': '#cb4b16',
    '--color-board-yellow': '#b58900',
    '--color-board-green': '#859900',
    '--color-board-purple': '#6c71c4',
    '--color-board-cyan': '#2aa198',
    '--color-board-teal': '#2aa198',
    '--color-phase-specify': '#268bd2',
    '--color-phase-plan': '#6c71c4',
    '--color-phase-tasks': '#cb4b16',
    '--color-phase-implement': '#718c00',
    '--color-phase-summary': '#d33682',
    '--color-phase-review': '#2aa198',
    '--color-phase-unknown': '#93a1a1',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.1)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.12)',
  },
};

// Catppuccin Latte — catppuccin.com
const catppuccinLatte: ThemeDefinition = {
  id: 'catppuccin-latte',
  name: 'Catppuccin Latte',
  category: 'light',
  colors: {
    '--color-board-bg': '#eff1f5',
    '--color-board-surface': '#e6e9ef',
    '--color-board-surface-hover': '#ccd0da',
    '--color-board-surface-alt': '#eff1f5',
    '--color-board-surface-elevated': '#bcc0cc',
    '--color-board-surface-overlay': '#acb0be',
    '--color-board-border': '#bcc0cc',
    '--color-board-border-hover': '#9ca0b0',
    '--color-board-text': '#1e1e2e',
    '--color-board-text-muted': '#303446',
    '--color-board-text-faint': '#9ca0b0',
    '--color-board-text-subtle': '#7c7f93',
    '--color-board-text-bright': '#11111b',
    '--color-board-accent': '#1e66f5',
    '--color-board-red': '#d20f39',
    '--color-board-orange': '#fe640b',
    '--color-board-yellow': '#df8e1d',
    '--color-board-green': '#40a02b',
    '--color-board-purple': '#8839ef',
    '--color-board-cyan': '#04a5e5',
    '--color-board-teal': '#179299',
    '--color-phase-specify': '#1e66f5',
    '--color-phase-plan': '#8839ef',
    '--color-phase-tasks': '#fe640b',
    '--color-phase-implement': '#40a02b',
    '--color-phase-summary': '#d20f39',
    '--color-phase-review': '#179299',
    '--color-phase-unknown': '#9ca0b0',
    '--shadow-card': '0 2px 8px rgba(0, 0, 0, 0.08)',
    '--shadow-card-hover': '0 6px 16px rgba(0, 0, 0, 0.1)',
  },
};

export const themes: readonly ThemeDefinition[] = [
  catppuccinMocha,
  radixMauve,
  dracula,
  tokyoNight,
  oneDark,
  rosePine,
  gruvboxDark,
  solarizedDark,
  solarizedLight,
  catppuccinLatte,
] as const;

export const darkThemes = themes.filter((t) => t.category === 'dark');
export const lightThemes = themes.filter((t) => t.category === 'light');

export function getThemeById(id: string): ThemeDefinition | undefined {
  return themes.find((t) => t.id === id);
}

export { DEFAULT_THEME_ID };
